/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 29 09:52:02 GMT 2020
 */

package com.nju.svcdisambiguation.serviceImp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.nju.svcdisambiguation.dataMapper.acm.ACMSearchMapper;
import com.nju.svcdisambiguation.dataMapper.ieee.IEEESearchMapper;
import com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld2;
import com.nju.svcdisambiguation.vo.AuthorVO;
import com.nju.svcdisambiguation.vo.PaperVO;
import com.nju.svcdisambiguation.vo.ResponseVO;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class SearchServiceImpOld2_ESTest extends SearchServiceImpOld2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArrayList<PaperVO> arrayList0 = new ArrayList<PaperVO>();
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(aCMSearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      ResponseVO responseVO0 = searchServiceImpOld2_0.searchByInstitutionName("~<9<~.aPu%(O,<f4[M", (-1), (-12), 0, (-1), (-12));
      assertNull(responseVO0.getMessage());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ArrayList<PaperVO> arrayList0 = new ArrayList<PaperVO>();
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(aCMSearchMapper0).selectPaperVOByAuthorName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      ResponseVO responseVO0 = searchServiceImpOld2_0.searchByAuthorName("[\"r`t|BOCi`", 2258, 2258, 0, 2258, 2258);
      assertTrue(responseVO0.getSuccess());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ArrayList<PaperVO> arrayList0 = new ArrayList<PaperVO>();
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(aCMSearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      // Undeclared exception!
      try { 
        searchServiceImpOld2_0.searchByInstitutionName("com.nju.svcdisambiguation.vo.ResponseVO", 0, 1923, 0, 940, 940);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1923
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld2", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ArrayList<PaperVO> arrayList0 = new ArrayList<PaperVO>();
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList<AuthorVO>) null, (ArrayList<AuthorVO>) null).when(aCMSearchMapper0).selectAuthorsByDocId(anyInt());
      doReturn(arrayList0).when(aCMSearchMapper0).selectPaperVOByAuthorName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      PaperVO paperVO0 = new PaperVO(0, "ACM", "ACM", "ACM", "ACM", 0, 0, (ArrayList<AuthorVO>) null, "ACM");
      arrayList0.add(paperVO0);
      ResponseVO responseVO0 = searchServiceImpOld2_0.searchByAuthorName("XT.F*", 1, 2258, 2258, 5997, 2258);
      assertNull(responseVO0.getMessage());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ArrayList<PaperVO> arrayList0 = new ArrayList<PaperVO>();
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null, (ArrayList) null).when(iEEESearchMapper0).selectAuthorsByDocId(anyInt());
      doReturn(arrayList0).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(aCMSearchMapper0).selectPaperVOByAuthorName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      PaperVO paperVO0 = new PaperVO(0, "ACr", "ACr", "ACr", "ACr", 0, 0, (ArrayList<AuthorVO>) null, "ACr");
      arrayList0.add(paperVO0);
      ResponseVO responseVO0 = searchServiceImpOld2_0.searchByAuthorName("XT.F*", 1, 2258, 2258, 5997, 2258);
      assertNull(responseVO0.getMessage());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ArrayList<PaperVO> arrayList0 = new ArrayList<PaperVO>();
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      PaperVO paperVO0 = new PaperVO();
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(aCMSearchMapper0).selectPaperVOByAuthorName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      arrayList0.add(paperVO0);
      // Undeclared exception!
      try { 
        searchServiceImpOld2_0.searchByAuthorName("XT.F*", 1, 2258, 2258, 5997, 2258);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ArrayList<PaperVO> arrayList0 = new ArrayList<PaperVO>();
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(aCMSearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      ResponseVO responseVO0 = searchServiceImpOld2_0.searchByInstitutionName("com.nju.svcdisambiguation.vo.PaperVO", (-7495), 0, (-7495), 0, 0);
      assertTrue(responseVO0.getSuccess());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ArrayList<PaperVO> arrayList0 = new ArrayList<PaperVO>();
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn(arrayList0).when(aCMSearchMapper0).selectPaperVOByAuthorName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      ResponseVO responseVO0 = searchServiceImpOld2_0.searchByAuthorName((String) null, (-7495), 0, 0, 0, 532);
      assertTrue(responseVO0.getSuccess());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(aCMSearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2((IEEESearchMapper) null, aCMSearchMapper0);
      // Undeclared exception!
      try { 
        searchServiceImpOld2_0.searchByInstitutionName((String) null, 0, (-765), (-2310), 0, (-2310));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld2", e);
      }
  }
}
