/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 08 11:54:04 GMT 2022
 */

package com.nju.svcdisambiguation.serviceImp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.nju.svcdisambiguation.serviceImp.YearCmp;
import com.nju.svcdisambiguation.vo.AuthorVO;
import com.nju.svcdisambiguation.vo.PaperVO;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class YearCmp_ESTest extends YearCmp_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      YearCmp yearCmp0 = new YearCmp();
      // Undeclared exception!
      try { 
        yearCmp0.compare((Object) null, (Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.YearCmp", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      YearCmp yearCmp0 = new YearCmp();
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        yearCmp0.compare("", object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.nju.svcdisambiguation.vo.PaperVO
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.YearCmp", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PaperVO paperVO0 = new PaperVO();
      ArrayList<AuthorVO> arrayList0 = new ArrayList<AuthorVO>();
      YearCmp yearCmp0 = new YearCmp();
      PaperVO paperVO1 = new PaperVO((-2175), "I+5?Ns", "I+5?Ns", "I+5?Ns", "I+5?Ns", (-2175), (-2175), arrayList0, "I+5?Ns");
      int int0 = yearCmp0.compare(paperVO1, paperVO0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PaperVO paperVO0 = new PaperVO();
      ArrayList<AuthorVO> arrayList0 = new ArrayList<AuthorVO>();
      YearCmp yearCmp0 = new YearCmp();
      PaperVO paperVO1 = new PaperVO(1039, "p+5?Ns", "p+5?Ns", "p+5?Ns", "p+5?Ns", 1039, 1039, arrayList0, "p+5?Ns");
      int int0 = yearCmp0.compare(paperVO1, paperVO0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      YearCmp yearCmp0 = new YearCmp();
      PaperVO paperVO0 = new PaperVO();
      int int0 = yearCmp0.compare(paperVO0, paperVO0);
      assertEquals(0, int0);
  }
}
