####################################
#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      discovery:
#        enabled: true
#      server:
#        git:
#          uri: https://github.com/tzs919/config.git
#          searchPaths: cargoservice,customerservice
#          username: tzs919
#          password: 123456


####################################
server:
  port: 8088
spring:
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          #              searchLocations: file://
          searchLocations: classpath:config/svc-consumer,classpath:config/svc-provider,classpath:config/svc-disambiguation,classpath:config/svc-prediction,classpath:config/svc-recommend