/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 08 11:49:47 GMT 2022
 */

package com.nju.svcdisambiguation.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.nju.svcdisambiguation.controller.AuthorDetailController;
import com.nju.svcdisambiguation.dataMapper.acm.ACMAuthorDetailMapper;
import com.nju.svcdisambiguation.dataMapper.ieee.IEEEAuthorDetailMapper;
import com.nju.svcdisambiguation.service.AuthorDetailService;
import com.nju.svcdisambiguation.serviceImp.AuthorDetailServiceImp;
import com.nju.svcdisambiguation.vo.ResponseVO;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class AuthorDetailController_ESTest extends AuthorDetailController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IEEEAuthorDetailMapper iEEEAuthorDetailMapper0 = mock(IEEEAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEEAuthorDetailMapper0).selectPaperVOByAuthorId(anyInt());
      ACMAuthorDetailMapper aCMAuthorDetailMapper0 = mock(ACMAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      AuthorDetailServiceImp authorDetailServiceImp0 = new AuthorDetailServiceImp(iEEEAuthorDetailMapper0, aCMAuthorDetailMapper0);
      AuthorDetailController authorDetailController0 = new AuthorDetailController(authorDetailServiceImp0);
      // Undeclared exception!
      try { 
        authorDetailController0.getAuthorPapers(1281, "%,b[fAdv^SG]#", 0, (-1586));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.AuthorDetailServiceImp", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IEEEAuthorDetailMapper iEEEAuthorDetailMapper0 = mock(IEEEAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEEAuthorDetailMapper0).selectReferenceVOByAuthorId(anyInt() , anyInt() , anyInt());
      ACMAuthorDetailMapper aCMAuthorDetailMapper0 = mock(ACMAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      AuthorDetailServiceImp authorDetailServiceImp0 = new AuthorDetailServiceImp(iEEEAuthorDetailMapper0, aCMAuthorDetailMapper0);
      AuthorDetailController authorDetailController0 = new AuthorDetailController(authorDetailServiceImp0);
      // Undeclared exception!
      try { 
        authorDetailController0.getAuthorRefer(1, "", 2836, 3338);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.AuthorDetailServiceImp", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IEEEAuthorDetailMapper iEEEAuthorDetailMapper0 = mock(IEEEAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEEAuthorDetailMapper0).selectAuthorInstitutions(anyInt());
      ACMAuthorDetailMapper aCMAuthorDetailMapper0 = mock(ACMAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      AuthorDetailServiceImp authorDetailServiceImp0 = new AuthorDetailServiceImp(iEEEAuthorDetailMapper0, aCMAuthorDetailMapper0);
      AuthorDetailController authorDetailController0 = new AuthorDetailController(authorDetailServiceImp0);
      ResponseVO responseVO0 = authorDetailController0.getAuthorInstitutions((-1), "Z<S");
      assertTrue(responseVO0.getSuccess());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IEEEAuthorDetailMapper iEEEAuthorDetailMapper0 = mock(IEEEAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      doReturn((Integer) null).when(iEEEAuthorDetailMapper0).selectDocCnt(anyInt());
      ACMAuthorDetailMapper aCMAuthorDetailMapper0 = mock(ACMAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      AuthorDetailServiceImp authorDetailServiceImp0 = new AuthorDetailServiceImp(iEEEAuthorDetailMapper0, aCMAuthorDetailMapper0);
      AuthorDetailController authorDetailController0 = new AuthorDetailController(authorDetailServiceImp0);
      // Undeclared exception!
      try { 
        authorDetailController0.getAuthorInfluence((-1), "oeS|-wN*-b9_/d");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.AuthorDetailServiceImp", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      IEEEAuthorDetailMapper iEEEAuthorDetailMapper0 = mock(IEEEAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEEAuthorDetailMapper0).selectFieldSummaryPOByAuthorId(anyInt());
      ACMAuthorDetailMapper aCMAuthorDetailMapper0 = mock(ACMAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      AuthorDetailServiceImp authorDetailServiceImp0 = new AuthorDetailServiceImp(iEEEAuthorDetailMapper0, aCMAuthorDetailMapper0);
      AuthorDetailController authorDetailController0 = new AuthorDetailController(authorDetailServiceImp0);
      // Undeclared exception!
      try { 
        authorDetailController0.getAuthorFieldSummary(2836, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.AuthorDetailServiceImp", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AuthorDetailController authorDetailController0 = new AuthorDetailController((AuthorDetailService) null);
      // Undeclared exception!
      try { 
        authorDetailController0.getAuthorReferred(0, "ezyM#;U^/%?~@5`K");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.controller.AuthorDetailController", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AuthorDetailController authorDetailController0 = new AuthorDetailController((AuthorDetailService) null);
      // Undeclared exception!
      try { 
        authorDetailController0.getAuthorPublicationSummary((-2543), "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.controller.AuthorDetailController", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      IEEEAuthorDetailMapper iEEEAuthorDetailMapper0 = mock(IEEEAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEEAuthorDetailMapper0).selectPaperVOByAuthorId(anyInt());
      AuthorDetailServiceImp authorDetailServiceImp0 = new AuthorDetailServiceImp(iEEEAuthorDetailMapper0, (ACMAuthorDetailMapper) null);
      AuthorDetailController authorDetailController0 = new AuthorDetailController(authorDetailServiceImp0);
      // Undeclared exception!
      try { 
        authorDetailController0.getAuthorPapers((-1409), "UQP", (-1409), 3331);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.AuthorDetailServiceImp", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IEEEAuthorDetailMapper iEEEAuthorDetailMapper0 = mock(IEEEAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      doReturn((Integer) null).when(iEEEAuthorDetailMapper0).selectAuthorReferred(anyInt());
      ACMAuthorDetailMapper aCMAuthorDetailMapper0 = mock(ACMAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      AuthorDetailServiceImp authorDetailServiceImp0 = new AuthorDetailServiceImp(iEEEAuthorDetailMapper0, aCMAuthorDetailMapper0);
      AuthorDetailController authorDetailController0 = new AuthorDetailController(authorDetailServiceImp0);
      // Undeclared exception!
      try { 
        authorDetailController0.getAuthorReferred(0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.AuthorDetailServiceImp", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AuthorDetailController authorDetailController0 = new AuthorDetailController((AuthorDetailService) null);
      // Undeclared exception!
      try { 
        authorDetailController0.getAuthorInstitutions((-1), "#>bhG,^GI*Ju");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.controller.AuthorDetailController", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IEEEAuthorDetailMapper iEEEAuthorDetailMapper0 = mock(IEEEAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEEAuthorDetailMapper0).selectAuthorPublicationSummaryByAuthorId(anyInt());
      ACMAuthorDetailMapper aCMAuthorDetailMapper0 = mock(ACMAuthorDetailMapper.class, new ViolatedAssumptionAnswer());
      AuthorDetailServiceImp authorDetailServiceImp0 = new AuthorDetailServiceImp(iEEEAuthorDetailMapper0, aCMAuthorDetailMapper0);
      AuthorDetailController authorDetailController0 = new AuthorDetailController(authorDetailServiceImp0);
      ResponseVO responseVO0 = authorDetailController0.getAuthorPublicationSummary(0, "%,b[fAdv^SG]#");
      assertNull(responseVO0.getMessage());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AuthorDetailController authorDetailController0 = new AuthorDetailController((AuthorDetailService) null);
      // Undeclared exception!
      try { 
        authorDetailController0.getAuthorDetail(1, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.controller.AuthorDetailController", e);
      }
  }
}
