/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 08 11:20:10 GMT 2022
 */

package com.nju.svcdisambiguation.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.nju.svcdisambiguation.controller.PaperDetailController;
import com.nju.svcdisambiguation.service.PaperDetailService;
import com.nju.svcdisambiguation.vo.ResponseVO;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class PaperDetailController_ESTest extends PaperDetailController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PaperDetailService paperDetailService0 = mock(PaperDetailService.class, new ViolatedAssumptionAnswer());
      doReturn((ResponseVO) null).when(paperDetailService0).getPaperRefer(anyInt() , anyString() , anyInt() , anyInt());
      PaperDetailController paperDetailController0 = new PaperDetailController(paperDetailService0);
      ResponseVO responseVO0 = paperDetailController0.getPaperRefer(2420, "DdxHlkfs", 886, 0);
      assertNull(responseVO0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PaperDetailService paperDetailService0 = mock(PaperDetailService.class, new ViolatedAssumptionAnswer());
      doReturn((ResponseVO) null).when(paperDetailService0).getPaperInfoByPaperId(anyInt() , anyString());
      PaperDetailController paperDetailController0 = new PaperDetailController(paperDetailService0);
      ResponseVO responseVO0 = paperDetailController0.getPaperInfoByPaperId(2420, "BU");
      assertNull(responseVO0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PaperDetailController paperDetailController0 = new PaperDetailController((PaperDetailService) null);
      // Undeclared exception!
      try { 
        paperDetailController0.getPaperRefer((-1607), "", (-1607), (-1607));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.controller.PaperDetailController", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PaperDetailController paperDetailController0 = new PaperDetailController((PaperDetailService) null);
      // Undeclared exception!
      try { 
        paperDetailController0.getPaperInfoByPaperId(1, "Content-Type");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.controller.PaperDetailController", e);
      }
  }
}
