/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 08 12:22:02 GMT 2022
 */

package com.nju.svcdisambiguation.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.nju.svcdisambiguation.controller.SearchController;
import com.nju.svcdisambiguation.dataMapper.acm.ACMSearchMapper;
import com.nju.svcdisambiguation.dataMapper.ieee.IEEESearchMapper;
import com.nju.svcdisambiguation.service.SearchService;
import com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld;
import com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld2;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class SearchController_ESTest extends SearchController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(aCMSearchMapper0).selectPaperVOByAuthorName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      SearchController searchController0 = new SearchController(searchServiceImpOld2_0);
      // Undeclared exception!
      try { 
        searchController0.searchByAuthorName("", 0, 0, 0, 1, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld2", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEESearchMapper0).selectIEEEPaperPOByAuthorName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      SearchServiceImpOld searchServiceImpOld0 = new SearchServiceImpOld(iEEESearchMapper0, aCMSearchMapper0);
      SearchController searchController0 = new SearchController(searchServiceImpOld0);
      // Undeclared exception!
      try { 
        searchController0.searchByAuthorName("com.nju.svcdisambiguation.vo.AuthorVO", (-3748), 142, (-3748), 142, (-3748));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(aCMSearchMapper0).selectPaperVOByAuthorName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      SearchController searchController0 = new SearchController(searchServiceImpOld2_0);
      // Undeclared exception!
      try { 
        searchController0.searchByAuthorName("IEEE", 0, 0, (-2917), 0, 291);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld2", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SearchController searchController0 = new SearchController((SearchService) null);
      // Undeclared exception!
      try { 
        searchController0.searchByInstitutionName("", (-770), (-770), (-770), (-770), (-770));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.controller.SearchController", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(aCMSearchMapper0).selectACMPaperPOByInstitutionName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld searchServiceImpOld0 = new SearchServiceImpOld(iEEESearchMapper0, aCMSearchMapper0);
      SearchController searchController0 = new SearchController(searchServiceImpOld0);
      // Undeclared exception!
      try { 
        searchController0.searchByInstitutionName("-eNS", 1, 1, 1, 1, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(aCMSearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      SearchController searchController0 = new SearchController(searchServiceImpOld2_0);
      // Undeclared exception!
      try { 
        searchController0.searchByInstitutionName("", (-3518), 270, (-2917), 291, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld2", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      IEEESearchMapper iEEESearchMapper0 = mock(IEEESearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(iEEESearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      ACMSearchMapper aCMSearchMapper0 = mock(ACMSearchMapper.class, new ViolatedAssumptionAnswer());
      doReturn((ArrayList) null).when(aCMSearchMapper0).selectPaperVOByInsName(anyString() , anyInt() , anyInt());
      SearchServiceImpOld2 searchServiceImpOld2_0 = new SearchServiceImpOld2(iEEESearchMapper0, aCMSearchMapper0);
      SearchController searchController0 = new SearchController(searchServiceImpOld2_0);
      // Undeclared exception!
      try { 
        searchController0.searchByInstitutionName("IEEE", 3364, 270, 3364, 270, 270);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.nju.svcdisambiguation.serviceImp.SearchServiceImpOld2", e);
      }
  }
}
