/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 28 09:10:03 GMT 2020
 */

package com.nju.svcrecommend.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import com.nju.svcrecommend.domain.ReviewerReq;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class ReviewerReq_ESTest extends ReviewerReq_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq();
      String string0 = reviewerReq0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq();
      reviewerReq0.setPublication("zTs%~wQgK");
      String string0 = reviewerReq0.getPublication();
      assertEquals("zTs%~wQgK", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq((String) null, (String) null, "v6", "!g?E-.<|");
      assertEquals("!g?E-.<|", reviewerReq0.getPublication());
      
      reviewerReq0.setPublication("");
      reviewerReq0.getPublication();
      assertEquals("v6", reviewerReq0.getKeywords());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq();
      String string0 = reviewerReq0.getKeywords();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq();
      reviewerReq0.setKeywords("CIw5@Z`I'");
      String string0 = reviewerReq0.getKeywords();
      assertEquals("CIw5@Z`I'", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq();
      String string0 = reviewerReq0.getAuthors();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq();
      reviewerReq0.setAuthors("zTs%~wQgK");
      String string0 = reviewerReq0.getAuthors();
      assertEquals("zTs%~wQgK", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq("", "", "", (String) null);
      String string0 = reviewerReq0.getPublication();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq("", "", "", (String) null);
      String string0 = reviewerReq0.getAuthors();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq("", "", "", (String) null);
      String string0 = reviewerReq0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq("", "", "", (String) null);
      String string0 = reviewerReq0.getKeywords();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ReviewerReq reviewerReq0 = new ReviewerReq("", "", "", (String) null);
      reviewerReq0.setTitle("2Cj!J;QXQ+w9$");
      String string0 = reviewerReq0.getTitle();
      assertEquals("2Cj!J;QXQ+w9$", string0);
  }
}
