version: '2'
services:
  eurekaserver:
    image: example/eurekasvr:section14
    ports:
      - "8761:8761"
  configserver:
    image: example/confsvr:section14
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123abc"
      POSTGRES_DB:       "postgres"
  cargoservice:
    image: example/cargo-service:section14
    ports:
      - "8080:8080"
    environment:
      PROFILE: "prod"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      DATABASESERVER_PORT: "5432"
  #    depends_on:
  #      - configserver
  #      - database
  customerservice:
    image: example/customer-service:section14
    ports:
      - "8085:8085"
    environment:
      PROFILE: "prod"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      DATABASESERVER_PORT: "5432"
