server:
  port: 8884
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# MyBatis
mybatis:
  typeAliasesPackage: com.nju.svcprediction.domain
#  mapperLocations: classpath:mapper/**/**.xml
#  configuration-properties: spring.datasource.ieee.*
